USE [master]
GO
/****** Object:  Database [Sehlang]    Script Date: 10/20/2025 4:55:32 PM ******/
CREATE DATABASE [Sehlang]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Sehlang', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Sehlang.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Sehlang_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Sehlang_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Sehlang] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Sehlang].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Sehlang] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Sehlang] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Sehlang] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Sehlang] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Sehlang] SET ARITHABORT OFF 
GO
ALTER DATABASE [Sehlang] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Sehlang] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Sehlang] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Sehlang] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Sehlang] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Sehlang] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Sehlang] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Sehlang] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Sehlang] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Sehlang] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Sehlang] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Sehlang] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Sehlang] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Sehlang] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Sehlang] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Sehlang] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Sehlang] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Sehlang] SET RECOVERY FULL 
GO
ALTER DATABASE [Sehlang] SET  MULTI_USER 
GO
ALTER DATABASE [Sehlang] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Sehlang] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Sehlang] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Sehlang] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Sehlang] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Sehlang] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Sehlang', N'ON'
GO
ALTER DATABASE [Sehlang] SET QUERY_STORE = ON
GO
-- Query Store configuration tanpa WAIT_STATS_CAPTURE_MODE yang bermasalah
ALTER DATABASE [Sehlang] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200)
GO
USE [Sehlang]
GO
/****** Object:  Table [dbo].[Barang]    Script Date: 10/20/2025 4:55:32 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Barang](
	[id_barang] [int] IDENTITY(1,1) NOT NULL,
	[nama_barang] [varchar](50) NOT NULL,
	[tgl] [date] NOT NULL,
	[harga_awal] [int] NOT NULL,
	[deskripsi_barang] [varchar](250) NOT NULL,
 CONSTRAINT [PK_Barang] PRIMARY KEY CLUSTERED 
(
	[id_barang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HistoryLelang]    Script Date: 10/20/2025 4:55:32 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HistoryLelang](
	[id_history] [int] IDENTITY(1,1) NOT NULL,
	[id_lelang] [int] NOT NULL,
	[id_barang] [int] NOT NULL,
	[id_user] [int] NOT NULL,
	[penawaran_harga] [int] NOT NULL,
 CONSTRAINT [PK_HistoryLelang] PRIMARY KEY CLUSTERED 
(
	[id_history] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Lelang]    Script Date: 10/20/2025 4:55:32 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Lelang](
	[id_lelang] [int] IDENTITY(1,1) NOT NULL,
	[id_barang] [int] NOT NULL,
	[tgl_lelang] [date] NOT NULL,
	[harga_akhir] [int] NULL,
	[id_user] [int] NULL,
	[id_petugas] [int] NOT NULL,
	[status] [varchar](10) NOT NULL,
 CONSTRAINT [PK_Lelang] PRIMARY KEY CLUSTERED 
(
	[id_lelang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Level]    Script Date: 10/20/2025 4:55:32 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Level](
	[id_level] [int] IDENTITY(1,1) NOT NULL,
	[level] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Level] PRIMARY KEY CLUSTERED 
(
	[id_level] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Masyarakat]    Script Date: 10/20/2025 4:55:32 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Masyarakat](
	[id_user] [int] IDENTITY(1,1) NOT NULL,
	[namaLengkap] [varchar](50) NOT NULL,
	[username] [varchar](50) NOT NULL,
	[password] [varchar](50) NOT NULL,
	[telp] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Masyarakat] PRIMARY KEY CLUSTERED 
(
	[id_user] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Petugas]    Script Date: 10/20/2025 4:55:32 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Petugas](
	[id_petugas] [int] IDENTITY(1,1) NOT NULL,
	[nama_petugas] [varchar](50) NOT NULL,
	[username] [varchar](50) NOT NULL,
	[password] [varchar](50) NOT NULL,
	[id_level] [int] NOT NULL,
 CONSTRAINT [PK_Petugas] PRIMARY KEY CLUSTERED 
(
	[id_petugas] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HistoryLelang]  WITH CHECK ADD  CONSTRAINT [FK_HistoryLelang_Barang] FOREIGN KEY([id_barang])
REFERENCES [dbo].[Barang] ([id_barang])
GO
ALTER TABLE [dbo].[HistoryLelang] CHECK CONSTRAINT [FK_HistoryLelang_Barang]
GO
ALTER TABLE [dbo].[HistoryLelang]  WITH CHECK ADD  CONSTRAINT [FK_HistoryLelang_Lelang] FOREIGN KEY([id_lelang])
REFERENCES [dbo].[Lelang] ([id_lelang])
GO
ALTER TABLE [dbo].[HistoryLelang] CHECK CONSTRAINT [FK_HistoryLelang_Lelang]
GO
ALTER TABLE [dbo].[HistoryLelang]  WITH CHECK ADD  CONSTRAINT [FK_HistoryLelang_Masyarakat] FOREIGN KEY([id_user])
REFERENCES [dbo].[Masyarakat] ([id_user])
GO
ALTER TABLE [dbo].[HistoryLelang] CHECK CONSTRAINT [FK_HistoryLelang_Masyarakat]
GO
ALTER TABLE [dbo].[Lelang]  WITH CHECK ADD  CONSTRAINT [FK_Lelang_Barang] FOREIGN KEY([id_barang])
REFERENCES [dbo].[Barang] ([id_barang])
GO
ALTER TABLE [dbo].[Lelang] CHECK CONSTRAINT [FK_Lelang_Barang]
GO
ALTER TABLE [dbo].[Lelang]  WITH CHECK ADD  CONSTRAINT [FK_Lelang_Masyarakat] FOREIGN KEY([id_user])
REFERENCES [dbo].[Masyarakat] ([id_user])
GO
ALTER TABLE [dbo].[Lelang] CHECK CONSTRAINT [FK_Lelang_Masyarakat]
GO
ALTER TABLE [dbo].[Lelang]  WITH CHECK ADD  CONSTRAINT [FK_Lelang_Petugas] FOREIGN KEY([id_petugas])
REFERENCES [dbo].[Petugas] ([id_petugas])
GO
ALTER TABLE [dbo].[Lelang] CHECK CONSTRAINT [FK_Lelang_Petugas]
GO
ALTER TABLE [dbo].[Petugas]  WITH CHECK ADD  CONSTRAINT [FK_Petugas_Level] FOREIGN KEY([id_level])
REFERENCES [dbo].[Level] ([id_level])
GO
ALTER TABLE [dbo].[Petugas] CHECK CONSTRAINT [FK_Petugas_Level]
GO
USE [master]
GO
ALTER DATABASE [Sehlang] SET  READ_WRITE 
GO
